src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Number_of_Contacts__c</fullName>
        <description>Total number of Contacts for the Account</description>
        <label>Number of Contacts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Bronze</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountProcessorTest.cls
@IsTest
public class AccountProcessorTest {

    @IsTest
    private static void testAccountContactList(){
        Account a = new Account();
        a.Name = 'Test Account';
        a.SLA__c = 'Gold';
        insert a;

        Contact con = new Contact();
        con.AccountId = a.Id;
        con.LastName = 'LastName';
 		insert con;
        
        List<Id> acctIdList = new List<Id>();
        acctIdList.add(a.Id);
        
        Test.startTest();
        	AccountProcessor.countContacts(acctIdList);
        Test.stopTest();
        
        Account acctWithContacts = [SELECT Number_of_Contacts__c FROM Account WHERE Id = :a.Id LIMIT 1];
    	System.assertEquals(1, acctWithContacts.Number_of_Contacts__c);

    }
}